{
    "title":        "://argon.red",
    "url":          "https://argon.red",
    "baseurl":      "",
    "permalink":    "/posts/:slug",

    "lang":         "zh",
    "timezone":     "Asia/Shanghai",
    "date_format":  "%Y/%m/%d",

    "defaults": [{
        "scope":    { "path": "" },
        "values":   { "layout": "default" }
    }],

    "sass": {
        "style":    "compressed",
    }

    "include":      [ "_pages" ],
    "exclude":      [ "Gemfile", "CNAME", "LICENSE", "README.md" ],

    "markdown":     "GFM",

    "kramdown": {
        "smart_quotes": [ "apos", "apos", "quot", "quot" ]  #  This is annoying for a typographer.

    }
}
