{
    "title":        "://argon.red",
    "url":          "https://argon.red",
    "baseurl":      "",
    "permalink":    "/:slug",

    "lang":         "zh",
    "timezone":     "Asia/Shanghai",
    "date_format":  "%Y/%m/%d",

    "defaults": [{
        "scope": {"path": ""},
        "values": {"layout": "default"}
    }]
}
