{
    "title":        "://argon.red",
    "url":          "https://argon.red",
    "baseurl":      "/test",
    "permalink":    "/posts/:slug",

    "lang":         "zh",
    "timezone":     "Asia/Shanghai",
    "date_format":  "%Y/%m/%d",

    "defaults": [{
        "scope": {"path": ""},
        "values": {"layout": "default"}
    }],

    "markdown":     "GFM",

    "kramdown": {  #  In case you want to use kramdown
        #  That’s annoying for a typographer.
        "smart_quotes": ["apos", "apos", "quot", "quot"]
    }
}
