{
    "title":        "://argon.red",
    "url":          "https://argon.red",
    "baseurl":      "",
    "permalink":    "/posts/:slug",

    "lang":         "zh",
    "timezone":     "Asia/Shanghai",
    "date_format":  "%Y/%m/%d",

    "defaults": [{
        "scope":    { "path": "" },
        "values":   { "layout": "default" }
    }],

    "kramdown": {
        #  This is annoying for a typographer.
        "smart_quotes": [ "apos", "apos", "quot", "quot" ]
    }
}
