title:      "test"
url:        "https://argon.red"
baseurl:    "/test"

permalink:  "/:slug"

favicon:    "logo.png"

theme:      "test"

theme_config:
  date_format:  "%Y/%m/%d"

sass:
  style:        ":compressed"
